### ISSUE TITLE
travis-cargo is not mentioned

### ISSUE THREAD

**Issue by gnzlbg** [sunjay/sunjay.github.io#1]
Since travis-cargo automatically handles travis + coveralls integration, shouldn't it be covered in the article? (If travis-cargo is not up-to-date it might be worth to update it).

**Comment by sunjay** [comment]
Thanks for pointing that out! I added a note about travis-cargo to both the [Travis CI Integration](http://sunjay.ca/2016/07/25/rust-code-coverage#travis-ci-integration) section and the [Codecov Integration](http://sunjay.ca/2016/07/25/rust-code-coverage#codecov-integration) section.

See https://github.com/sunjay/sunjay.github.io/commit/038fd294f8c225fea57acfb72d096bd765f42191 for the exact diff.
