### ISSUE TITLE
Additional dependency apt install zlib1g-dev (rust-code-coverage)

### ISSUE THREAD

**Issue by jeanphilippeD** [sunjay/sunjay.github.io#3]
Hello,
About, http://sunjay.ca/2016/07/25/rust-code-coverage

This commit added dependency on zlib that require 'apt install zlib1g-dev'
https://github.com/SimonKagstrom/kcov/commit/187fc7cb4fb43157b1634d4b3430a9a9a3c49033

Kind Regards,
Jean-Philippe

**Comment by sunjay** [comment]
Thanks for reporting this! I added it in https://github.com/sunjay/sunjay.github.io/pull/4
